ansible_python_interpreter: /usr/bin/python3
username: ywngr
home: /home/{{ username }}
archive_name: archive
archive_path: "{{ home }}/{{ archive_name }}"
archive_1tb_name: archive_tb
archive_1tb_path: "{{ home }}/{{ archive_1tb_name }}"
dotfiles_repo: https://github.com/ywngrr/dotfiles.git
dotfiles_dir: /home/{{ username }}/.dotfiles
kernel_opts: "acpi_backlight=native mitigations=off"
ansible_user: ansible_user
ansible_git_name: ansible_arch_laptop
ansible_path: "{{ home }}/{{ ansible_git_name }}"
