- name: Arch Linux laptop setup
  hosts: localhost

  roles:
    - base
    - shell
#    - zsh
    - kde
    - kitty
    - power
    - systemd-boot
    - rclone
    - ssh
    - keepassxc
    - git
    - firefox
    - steam
#    - aur
#    - audio
#    - fonts
#    - dotfiles
