- name: Arch Linux laptop setup
  hosts: localhost
  roles:
    - { role: base, tags: ['base'] }
    - { role: users, tags: ['users'] }
    - { role: shell, tags: ['shell'] }
    - { role: kde, tags: ['kde'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: power, tags: ['power'] }
    - { role: systemd-boot, tags: ['systemd-boot'] }
    - { role: rclone, tags: ['rclone'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: keepassxc, tags: ['keepassxc'] }
    - { role: git, tags: ['git'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: steam, tags: ['steam'] }
    - { role: nintendoswitch, tags: ['nintendoswitch'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: nicotine, tags: ['nicotine'] }
    - { role: aur, tags: ['aur'] }
    - { role: states, tags: ['states'] }
    - { role: strawberry, tags: ['strawberry'] }
#    - { role: zsh, tags: ['zsh'] }
#    - audio
#    - fonts
#    - dotfiles
