- name: Reload systemd in user scope
  systemd_service:
    daemon_reload: true
    scope: user

- name: Reload systemd
  become: true
  systemd_service:
    daemon_reload: true

- name: Upgrade arch system
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Update locale
  become: true
  command: locale-gen
