- name: Create config folder
  file:
    path: "{{ home }}/.config/strawberry"
    state: directory

- name: Include custom config
  blockinfile:
    path: "{{ home }}/.config/strawberry/strawberry.conf"
    block: "{{ lookup('template', 'files/include_config') }}"
    insertafter: EOF
