- name: Download emulators from dropbox
  shell: |
    rclone copy db:Apps/{{ item }} {{ home }}/{{ archive_name }}/Apps/
    chmod 755 {{ home }}/{{ archive_name }}/Apps/{{ item }}
  args:
    creates: "{{ home }}/{{ archive_name }}/Apps/{{ item }}"
  loop:
    - Ryujinx.AppImage
    - Citron.AppImage

- name: Copy .desktop files
  template:
    src: "templates/{{ item }}.desktop"
    dest: "{{ home}}/.local/share/applications/"
  loop:
    - ryujinx
    - citron

